/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated.tools'
import { Route as AuthenticatedToolsCategoryToolRouteImport } from './routes/_authenticated.tools.$category.$tool'
import { Route as AuthenticatedToolsCategoryToolEditRouteImport } from './routes/_authenticated.tools.$category.$tool.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsCategoryToolRoute =
  AuthenticatedToolsCategoryToolRouteImport.update({
    id: '/$category/$tool',
    path: '/$category/$tool',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsCategoryToolEditRoute =
  AuthenticatedToolsCategoryToolEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedToolsCategoryToolRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/tools/$category/$tool': typeof AuthenticatedToolsCategoryToolRouteWithChildren
  '/tools/$category/$tool/edit': typeof AuthenticatedToolsCategoryToolEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/tools/$category/$tool': typeof AuthenticatedToolsCategoryToolRouteWithChildren
  '/tools/$category/$tool/edit': typeof AuthenticatedToolsCategoryToolEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tools/$category/$tool': typeof AuthenticatedToolsCategoryToolRouteWithChildren
  '/_authenticated/tools/$category/$tool/edit': typeof AuthenticatedToolsCategoryToolEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/tools'
    | '/users'
    | '/'
    | '/tools/$category/$tool'
    | '/tools/$category/$tool/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/tools'
    | '/users'
    | '/'
    | '/tools/$category/$tool'
    | '/tools/$category/$tool/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/tools'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/tools/$category/$tool'
    | '/_authenticated/tools/$category/$tool/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/$category/$tool': {
      id: '/_authenticated/tools/$category/$tool'
      path: '/$category/$tool'
      fullPath: '/tools/$category/$tool'
      preLoaderRoute: typeof AuthenticatedToolsCategoryToolRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/$category/$tool/edit': {
      id: '/_authenticated/tools/$category/$tool/edit'
      path: '/edit'
      fullPath: '/tools/$category/$tool/edit'
      preLoaderRoute: typeof AuthenticatedToolsCategoryToolEditRouteImport
      parentRoute: typeof AuthenticatedToolsCategoryToolRoute
    }
  }
}

interface AuthenticatedToolsCategoryToolRouteChildren {
  AuthenticatedToolsCategoryToolEditRoute: typeof AuthenticatedToolsCategoryToolEditRoute
}

const AuthenticatedToolsCategoryToolRouteChildren: AuthenticatedToolsCategoryToolRouteChildren =
  {
    AuthenticatedToolsCategoryToolEditRoute:
      AuthenticatedToolsCategoryToolEditRoute,
  }

const AuthenticatedToolsCategoryToolRouteWithChildren =
  AuthenticatedToolsCategoryToolRoute._addFileChildren(
    AuthenticatedToolsCategoryToolRouteChildren,
  )

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsCategoryToolRoute: typeof AuthenticatedToolsCategoryToolRouteWithChildren
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsCategoryToolRoute:
    AuthenticatedToolsCategoryToolRouteWithChildren,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
