name: Deploy to Firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd functions && npm ci
          cd ../web && npm ci
      
      - name: Build functions
        run: cd functions && npm run build
      
      - name: Clear TypeScript cache
        run: |
          rm -rf web/node_modules/.cache
          rm -rf web/dist
      
      - name: Type check web
        run: cd web && npx tsc --noEmit
      
      - name: Build web
        run: cd web && npm run build
      
      - name: Lint web
        run: cd web && npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd functions && npm ci
          cd ../web && npm ci
      
      - name: Clear TypeScript cache
        run: |
          rm -rf web/node_modules/.cache
          rm -rf web/dist
      
      - name: Type check web
        run: cd web && npx tsc --noEmit
      
      - name: Build functions
        run: cd functions && npm run build
      
      - name: Build web
        run: cd web && npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: tool-tracker-c8180
          channelId: live
          only: hosting,functions
